### ISSUE TITLE
v2.2.x Chore - Cleanup CI/CD Artifacts

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall-org/multicast#435]
## Context

As pointed out by AI:

> _🧹 Nitpick (assertive)_
>
> **Remove unused `BUILD-info.txt` creation**  
The `check_status` script appends to `BUILD-info.txt` (lines 318–319) but never uses or uploads this file. Consider removing these lines to reduce clutter.
>
> <details>
> <summary>🤖 Prompt for AI Agents</summary>
>
> ```
> In .github/workflows/CI-CHGLOG.yml at lines 318 to 319, the script appends to
the BUILD-info.txt file which is never used or uploaded later. Remove these
lines to eliminate the creation and appending of this unused file, thereby
reducing unnecessary clutter in the workflow.
> ```
> 
> </details>
> 
> 

_Originally posted by @coderabbitai[bot] in https://github.com/reactive-firewall-org/multicast/pull/433#discussion_r2135051144_

## Tasks

 - [ ] Cleanup `CI-CHGLOG.yml`
 - [ ] Cleanup `CI-MATs.yml`
 - [ ] Cleanup `CI-DOCs.yml`

 - [ ] (OPTIONAL) cleanup any related CI/CD configs with similar unused artifacts
 
 
 ## additional info
 
 * see also PR #433
 * see also #410 and #411 (hint: may need to adjust documentation after cleanup :shrug: )

**Comment by reactive-firewall** [comment]
> [!TIP]
> start with https://github.com/search?q=repo%3Areactive-firewall-org%2Fmulticast++%22Build-info.txt%22&type=code and plan from there

**Comment by reactive-firewall** [comment]
Relevant lines:

https://github.com/reactive-firewall-org/multicast/blob/794f02f5109c4f3eee7a38f5afd2fcb92f680f40/.github/workflows/CI-CHGLOG.yml#L319-L321

https://github.com/reactive-firewall-org/multicast/blob/794f02f5109c4f3eee7a38f5afd2fcb92f680f40/.github/workflows/CI-MATs.yml#L347-L349

https://github.com/reactive-firewall-org/multicast/blob/794f02f5109c4f3eee7a38f5afd2fcb92f680f40/.github/workflows/CI-DOCS.yml#L209-L214

https://github.com/reactive-firewall-org/multicast/blob/794f02f5109c4f3eee7a38f5afd2fcb92f680f40/.github/workflows/CI-DOCS.yml#L246-L255

```yaml
  merge:
    runs-on: ubuntu-latest
    needs: [check_mats, DOCS]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          pattern: Multicast-Documentation-${{ needs.check_mats.outputs.build_sha }}-*-*
          name: Multicast-Documentation-${{ needs.check_mats.outputs.build_sha }}-ALL
          delete-merged: true
          compression-level: 9
```
